#
###################################
# Site wide configuration
####################################
#
title: ./qaiser // STOPSHIP | *cough* Qaiser´s Tech Blog *cough*
email: q.abbasi1010 at gmail dot com
description: Qaiser´s Tech Blog
url: # the base hostname & protocol for your site

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Qaiser
  avatar: avatar.png
  job: Java dev @ codecentric
  bio: Crummy enterprise hipster in the daytime… Functional Programming avant-gardist in the night.
  email: q.abbasi1010 at gmail dot com
  disqus-shortname: disqus_Bxzjx799wS
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: qabbasi
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
